version: '3'

services:
  db:
    container_name: ova.db
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
    ports:
      - "5432:5432"
    volumes:
      - ./../storage/db:/var/lib/postgresql/data

  jaegert:
    container_name: ova.jaegert
    image: jaegertracing/all-in-one:latest
    restart: always
    ports:
      - "16686:16686"
      - "6831:6831/udp"
