// Code generated by MockGen. DO NOT EDIT.
// Source: method_repo.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	model "ova-method-api/internal/model"
	repo "ova-method-api/internal/repo"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMethodRepo is a mock of MethodRepo interface.
type MockMethodRepo struct {
	ctrl     *gomock.Controller
	recorder *MockMethodRepoMockRecorder
}

// MockMethodRepoMockRecorder is the mock recorder for MockMethodRepo.
type MockMethodRepoMockRecorder struct {
	mock *MockMethodRepo
}

// NewMockMethodRepo creates a new mock instance.
func NewMockMethodRepo(ctrl *gomock.Controller) *MockMethodRepo {
	mock := &MockMethodRepo{ctrl: ctrl}
	mock.recorder = &MockMethodRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMethodRepo) EXPECT() *MockMethodRepoMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockMethodRepo) Add(ctx context.Context, items []model.Method) ([]model.Method, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, items)
	ret0, _ := ret[0].([]model.Method)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Add indicates an expected call of Add.
func (mr *MockMethodRepoMockRecorder) Add(ctx, items interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockMethodRepo)(nil).Add), ctx, items)
}

// Describe mocks base method.
func (m *MockMethodRepo) Describe(ctx context.Context, id uint64) (*model.Method, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Describe", ctx, id)
	ret0, _ := ret[0].(*model.Method)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Describe indicates an expected call of Describe.
func (mr *MockMethodRepoMockRecorder) Describe(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Describe", reflect.TypeOf((*MockMethodRepo)(nil).Describe), ctx, id)
}

// List mocks base method.
func (m *MockMethodRepo) List(ctx context.Context, limit, offset uint64) ([]model.Method, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, limit, offset)
	ret0, _ := ret[0].([]model.Method)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockMethodRepoMockRecorder) List(ctx, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockMethodRepo)(nil).List), ctx, limit, offset)
}

// Remove mocks base method.
func (m *MockMethodRepo) Remove(ctx context.Context, id uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockMethodRepoMockRecorder) Remove(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockMethodRepo)(nil).Remove), ctx, id)
}

// Transaction mocks base method.
func (m *MockMethodRepo) Transaction(ctx context.Context, fn func(repo.MethodRepo) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// Transaction indicates an expected call of Transaction.
func (mr *MockMethodRepoMockRecorder) Transaction(ctx, fn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transaction", reflect.TypeOf((*MockMethodRepo)(nil).Transaction), ctx, fn)
}

// Update mocks base method.
func (m *MockMethodRepo) Update(ctx context.Context, id uint64, value string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockMethodRepoMockRecorder) Update(ctx, id, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMethodRepo)(nil).Update), ctx, id, value)
}
